### ISSUE TITLE
list_erase job requires array but ProcessJob turns that to string

### ISSUE THREAD

**Issue by xXBlackHawkXx** [sailthru/sailthru-net-client#35]
Using the .NET client, the ProcessJob method requires a hashtable of parameters. I have added the lists to delete as an array to the parameters. It looks like within the ProcessJob method it converts the hashtable value to string (ignoring that this value is an array) so that it can url encode it. In doing this we lose the array typing and receive the error ‘The lists parameter must be passed as an array’.

The syntax I have tried using is:

```
Hashtable jobParams = new Hashtable();
jobParams.Add( "lists", JsonConvert.SerializeObject( listsToDelete.ToArray() ) );
SailthruResponse response = client.ProcessJob( "list_erase", null, null, jobParams );
```

And

```
Hashtable jobParams = new Hashtable();
jobParams.Add( "lists", listsToDelete.ToArray() );
SailthruResponse response = client.ProcessJob( "list_erase", null, null, jobParams );
```

**Comment by kvainer** [comment]
Thanks for the report, going to look into it

**Comment by kvainer** [comment]
It looks like the majority of the methods encode the parameters into JSON but for some reason the one for jobs does not, will make a new release with the fix

**Comment by kvainer** [comment]
The latest release on Nuget now has the fix: https://www.nuget.org/packages/Sailthru.Client/
Thanks!
