### ISSUE TITLE
Exception on PostEvent call

### ISSUE THREAD

**Issue by jeremieDD** [sailthru/sailthru-net-client#37]
Error message `"Cannot access a disposed object. Object name: 'System.Net.HttpWebResponse'."`

This error occurs on file **Sailthru/Sailthru/SailthruResponse.cs**.
Function **parseJSON()**, object **webResponse** use on line 103 but the object disposed on line 82.

Best regards.

**Comment by kvainer** [comment]
Hi,

Thanks for the report, will look into it.

~Kirill

**Comment by kvainer** [comment]
@jeremieDD 

Hi, I'm not able to reproduce this issue. Can you please specify:

- Operating System
- .NET version

Thanks,
Kirill

**Comment by jeremieDD** [comment]
Hi,

I use the version 1.1.5 in azure function .NET Core 2.1

**Comment by kvainer** [comment]
Thanks, fixed in https://github.com/sailthru/sailthru-net-client/pull/41
