### ISSUE TITLE
BlastRequest class contains depricated fields

### ISSUE THREAD

**Issue by mkglobalspec** [sailthru/sailthru-net-client#47]
Models.BlastRequest has a deprecated field TestPercent which makes it impossible to make a valid request and ends up in error 99.

**Comment by kvainer** [comment]
Going to look into this. Thanks

**Comment by mkglobalspec** [comment]
`BlastRequest blastRequest = new BlastRequest();
blastRequest.Name = "Blast Name1";
blastRequest.ContentHtml = "<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. </p>";
blastRequest.List = "Sample List";
blastRequest.ContentText = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, ";
blastRequest.Subject = "Sample Subject";
blastRequest.ScheduleTime = "+3 hours";
blastRequest.FromName = "C# Client";
blastRequest.FromEmail = "no-reply@sailthru.com";

response = client.ScheduleBlast(blastRequest);`

**Comment by mkglobalspec** [comment]
Given a valid client connection and FromEmail

**Comment by kvainer** [comment]
Fixed in https://github.com/sailthru/sailthru-net-client/pull/59
