### ISSUE TITLE
SendRequest class is missing data_feed_url field listed in the docs

### ISSUE THREAD

**Issue by mkglobalspec** [sailthru/sailthru-net-client#48]
data_feed_url is a parameter that is listed in https://getstarted.sailthru.com/developers/api/send/. Could it be included in the class?

**Comment by kvainer** [comment]
Going to look into this. Thanks

**Comment by mkglobalspec** [comment]
Thank you!

**Comment by kvainer** [comment]
Fixed in https://github.com/sailthru/sailthru-net-client/pull/60
