### ISSUE TITLE
Interaction with api/list endpoint

### ISSUE THREAD

**Issue by mkglobalspec** [sailthru/sailthru-net-client#57]
It seems that the client does not support list manipulation currently. It would be helpful  if there was ListRequest class and applicable function in the client.

**Comment by aingram** [comment]
List membership is part of the `user` endpoint and the `list` endpoint is for the meta data of a list, e.g. its name. 

This should be what you need. Please re-open this issue if not: https://github.com/sailthru/sailthru-net-client/blob/master/Sailthru/Sailthru.Models/UserRequest.cs#L91
